# Generated by Django 5.2.9 on 2025-12-18 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade5', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pupilprofile',
            name='class_name',
        ),
        migrations.AddField(
            model_name='pupilprofile',
            name='classname',
            field=models.CharField(choices=[('5А', '5А'), ('5Б', '5Б'), ('5В', '5В')], default='5A', max_length=20, verbose_name='Класс'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pupilprofile',
            name='first_name',
            field=models.CharField(default='ff', max_length=50, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pupilprofile',
            name='last_name',
            field=models.CharField(default='s', max_length=50, verbose_name='Фамилия'),
            preserve_default=False,
        ),
    ]
