# Generated by Django 5.2.9 on 2025-12-18 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade5', '0003_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pupilprofile',
            name='classname',
            field=models.CharField(choices=[('5ВЭ', '5ВЭ'), ('5МИ', '5МИ'), ('5АВ', '5АВ'), ('5ЕМ', '5ЕМ')], default='5ВЭ', max_length=20, verbose_name='Класс'),
        ),
    ]
