# Generated by Django 5.2.9 on 2025-12-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade5', '0004_alter_pupilprofile_classname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pupilprofile',
            options={'verbose_name': 'Профиль ученика', 'verbose_name_plural': 'Профили учеников'},
        ),
        migrations.AlterField(
            model_name='pupilprofile',
            name='classname',
            field=models.CharField(choices=[('5ВЭ', '5ВЭ'), ('5МИ', '5МИ'), ('5АВ', '5АВ'), ('5ЕМ', '5ЕМ')], max_length=20, verbose_name='Класс'),
        ),
    ]
