# Generated by Django 5.2.9 on 2025-12-30 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grade5', '0005_alter_pupilprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskresult',
            options={'ordering': ['-created_at'], 'verbose_name': 'Результат задачи', 'verbose_name_plural': 'Результаты задач'},
        ),
    ]
